spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment
        uri: lb://payment
        predicates:
        - Path=/pay/**
        filters:
        - RewritePath=/pay/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-pay
            fallbackUri: forward:/fallback/serviceA
      - id: tax
        uri: lb://tax
        predicates:
        - Path=/tax/**
        filters:
        - RewritePath=/tax/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-tax
            fallbackUri: forward:/fallback/serviceB  
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
     
