spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment
        uri: lb://service-a
        predicates:
        - Path=/srva/**
        filters:
        - RewritePath=/srva/(?<segment>.*), /$\{segment}
      - id: tax
        uri: lb://service-b
        predicates:
        - Path=/srvb/**
        filters:
        - RewritePath=/srvb/(?<segment>.*), /$\{segment}
    consul:
      host: consul
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: info, health
     
